<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-23T22:35:27 IST" name="Default suite" finished-at="2022-06-23T22:37:37 IST" duration-ms="130019">
    <groups>
    </groups>
    <test started-at="2022-06-23T22:35:27 IST" name="Default test" finished-at="2022-06-23T22:37:37 IST" duration-ms="130019">
      <class name="com.crm.createContacts.CreateContactsTest">
        <test-method is-config="true" signature="dbConfig()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:35:27 IST" name="dbConfig" finished-at="2022-06-23T22:35:27 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbConfig -->
        <test-method is-config="true" signature="launchTheBrowser()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:35:27 IST" name="launchTheBrowser" finished-at="2022-06-23T22:35:32 IST" duration-ms="4745" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchTheBrowser -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:35:32 IST" name="loginToAppln" finished-at="2022-06-23T22:35:38 IST" duration-ms="6314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method retried="true" signature="createContactTest()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:35:38 IST" name="createContactTest" finished-at="2022-06-23T22:36:01 IST" duration-ms="22707" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.createContacts.CreateContactsTest.createContactTest(CreateContactsTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logoutFromAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:36:01 IST" name="logoutFromAppln" finished-at="2022-06-23T22:36:04 IST" duration-ms="3153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromAppln -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:36:04 IST" name="loginToAppln" finished-at="2022-06-23T22:36:09 IST" duration-ms="5042" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method retried="true" signature="createContactTest()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:36:09 IST" name="createContactTest" finished-at="2022-06-23T22:36:29 IST" duration-ms="19407" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.createContacts.CreateContactsTest.createContactTest(CreateContactsTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logoutFromAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:36:29 IST" name="logoutFromAppln" finished-at="2022-06-23T22:36:31 IST" duration-ms="2711" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromAppln -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:36:31 IST" name="loginToAppln" finished-at="2022-06-23T22:36:37 IST" duration-ms="5259" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method retried="true" signature="createContactTest()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:36:37 IST" name="createContactTest" finished-at="2022-06-23T22:36:59 IST" duration-ms="22729" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.createContacts.CreateContactsTest.createContactTest(CreateContactsTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logoutFromAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:36:59 IST" name="logoutFromAppln" finished-at="2022-06-23T22:37:04 IST" duration-ms="4958" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromAppln -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:37:04 IST" name="loginToAppln" finished-at="2022-06-23T22:37:10 IST" duration-ms="5490" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method signature="createContactTest()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:37:10 IST" name="createContactTest" finished-at="2022-06-23T22:37:32 IST" duration-ms="22636" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.createContacts.CreateContactsTest.createContactTest(CreateContactsTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logoutFromAppln()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:37:33 IST" name="logoutFromAppln" finished-at="2022-06-23T22:37:36 IST" duration-ms="2940" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromAppln -->
        <test-method is-config="true" signature="closeTheBrowser()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:37:36 IST" name="closeTheBrowser" finished-at="2022-06-23T22:37:37 IST" duration-ms="1204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTheBrowser -->
        <test-method is-config="true" signature="closeDBconfig()[pri:0, instance:com.crm.createContacts.CreateContactsTest@434a63ab]" started-at="2022-06-23T22:37:38 IST" name="closeDBconfig" finished-at="2022-06-23T22:37:38 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBconfig -->
      </class> <!-- com.crm.createContacts.CreateContactsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
